In [1]:
import torch

print(torch.__version__)

1.7.0


#### Get the current default floating point torch.dtype

In [2]:
torch.get_default_dtype()

torch.float32

#### default dtype for a tensor can only be a float type

In [3]:
torch.set_default_dtype(torch.int)

TypeError: only floating-point types are supported as the default type

#### The default floating point dtype is initially torch.float32
#### Set the default floating point to torch.float64

In [4]:
torch.set_default_dtype(torch.float64)

In [5]:
torch.get_default_dtype()

torch.float64

#### Creating Tensors

#### A Tensor initialized with a specific array, the torch tensor always creates a copy of the data

In [6]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])
#alias for torch.FloatTensor
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
torch.is_tensor(tensor_arr)

True

In [12]:
type(tensor_arr)

torch.Tensor

#### numel() returns the number of elements in a tensor

In [8]:
torch.numel(tensor_arr)

6

In [9]:
tensor_arr[1,2] #2nd row 3rd column (due to zero-index-start)

tensor(6.)

In [10]:
tensor_arr.shape # rows, cols

torch.Size([2, 3])

In [11]:
#only returns 1st dimension
len(tensor_arr)

2

#### An un-initialized Tensor of shape 2X2 allocated space in memory

In [15]:
tensor_uninitialized = torch.Tensor(2, 2) #create using shape

In [16]:
tensor_uninitialized #random values within tensor 

tensor([[0., 0.],
        [0., 0.]])

#### A tensor of size 2x2 initialized with random values

In [17]:
tensor_initialized = torch.rand(2, 2)

In [18]:
tensor_initialized

tensor([[0.3361, 0.9003],
        [0.4730, 0.3431]])

#### Tensors can be set to have specific data types

In [19]:
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor) 
tensor_int
#tensors for GPU use different classes e.g. torch.IntTensor.CUDA

tensor([5, 3], dtype=torch.int32)

#### A Tensor of type short

In [20]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])   
tensor_short #implicit conversion is deprecated

<ipython-input-20-cc07ff40659c>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])


tensor([1, 2, 3], dtype=torch.int16)

In [24]:
tensor_short = torch.Tensor([1.0, 2.0, 3.0], dtype=torch.int16)   
tensor_short #implicit conversion is deprecated

TypeError: new() received an invalid combination of arguments - got (list, dtype=torch.dtype), but expected one of:
 * (*, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)


#### A Tensor of type float half (float16)

In [25]:
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

#### A tensor filled with a specific values


In [26]:
tensor_fill = torch.full((2, 6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

#### A tensor of size (2,4) containing all ones

In [27]:
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

#### A tensor of size (2,4) like tensor_of_ones containing all zeroes

In [29]:
tensor_of_zeroes = torch.zeros_like(tensor_of_ones) #same shape
tensor_of_zeroes

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

#### Create an identity 5X5 tensor

In [30]:
tensor_eye = torch.eye(5) #identity matrix
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

#### Get the list of indices of non-zero elements in a tensor
[ i, j ] index for non-zero elements

In [31]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

#### Create a sparse tensor using coordinates specified by indices and values

In [32]:
i = torch.tensor([[0, 1, 1],
                  [2, 2, 0]])
#lowercase tensor

In [33]:
v = torch.tensor([3, 4, 5], dtype=torch.float32)

In [34]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])

In [38]:
sparse_tensor.data #underlying matrix
#different structure and layout [to save memory]
#values (zero-indexed) are populated into the indices tensor 
# e.g. all indices 0 will be replace with first element in values, 
# all 1s will be replaced with values[1] etc...

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

## Inplace / Out-of-place
The first difference is that ALL operations on the tensor that operate in-place on it will have an "\_" postfix. For example, add is the out-of-place version, and add\_ is the in-place version.

#### .fill_ is in-place operation and it doesnt have any out-place equivalent

In [40]:
initial_tensor = torch.rand(2, 3) 

initial_tensor

tensor([[0.3533, 0.6866, 0.7742],
        [0.3005, 0.7216, 0.7048]])

In [41]:
initial_tensor.fill_(10) 
#undescore suffix for operations that change in-place

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [43]:
initial_tensor.fill(10) #not all in-place operations have a corresponding 
# 'out-of-place' [returning] equivalent

AttributeError: 'Tensor' object has no attribute 'fill'

#### The add() method does an out-of-place add operation and returns a new tensor
This is assigned to the new_tensor variable

In [44]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

#### The original tensor is unchanged

In [45]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

#### The add\_ method does an in-place add, changing the calling tensor

In [46]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

#### The new_tensor was a separate copy and is unaffected

In [47]:
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

#### In-place version of sqrt()

In [48]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

### Indexing, Slicing, Joining, Mutating Ops

#### Slicing

In [50]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
#evenly spaced numbers between start and end
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

#### Splits a tensor into a specific number of chunks.
- tensor (Tensor) – the tensor to split
- chunks (int) – number of chunks to return
- dim (int) – dimension along which to split the tensor


In [51]:
tensor_chunk = torch.chunk(x, 3, 0)#3rd param is dimension for chunk operation
# bin into 3 parts
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

#### Concatenates the  sequence of tensors along the given dimension

All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [52]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])

torch.cat((tensor1, tensor2, tensor3), 0)# 0 is dimension for operation
#all dims must be same shape except the concat dimension

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [4]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [5]:
random_tensor[0, 1] # indexing

tensor(8.)

In [6]:
random_tensor[1:, 1:] #array slicing

tensor([[ 5.,  6.],
        [ 2., 21.]])

#### Splits the tensor into chunks

In [7]:
random_tensor_split = torch.split(random_tensor, 2)
random_tensor_split

(tensor([[10.,  8., 30.],
         [40.,  5.,  6.]]),
 tensor([[12.,  2., 21.]]))

#### View

In [57]:
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [58]:
random_tensor.size()

torch.Size([3, 3])

In [61]:
resized_tensor = random_tensor.view(9) 
#same underlying memory 
#must be compatible shape
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [59]:
resized_tensor = random_tensor.view(-1, 6)
#-1 means any number of rows in this example
resized_tensor

RuntimeError: shape '[-1, 6]' is invalid for input of size 9

In [62]:
resized_tensor.size()

torch.Size([9])

#### view() does not create a deep copy - just a view as the name suggests
Modifying the original tensor affects the resized_tensor as they both point to the same space in memory

In [63]:
random_tensor[2, 2] = 100.0
#value is changed in views of the original tensor
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

#### Unsqueeze
Returns a new tensor with a dimension of size one inserted at the specified position.

In [64]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [65]:
random_tensor.shape

torch.Size([3, 3])

In [156]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
#add dimensions
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [157]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

#### Transpose

#### Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

In [66]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [67]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
#flip/swap dimensions
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

#### Sorting tensors
Tensors can be sorted along a specified dimension. If no dimension is specified, the last dimension is picked by default

In [8]:
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [9]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)

In [10]:
sorted_tensor

tensor([[ 8., 10., 30.],
        [ 5.,  6., 40.],
        [ 2., 12., 21.]])

In [11]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

# Math Operations
Pytorch supports a number of mathematical operations which can be performed on tensors. We take a look at a few of them here

In [12]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000])

#### Absolute values

In [13]:
tensor_abs = torch.abs(tensor_float)      
tensor_abs

tensor([1.1000, 2.2000, 3.3000])

In [14]:
initial_tensor

NameError: name 'initial_tensor' is not defined

In [167]:
new_tensor = torch.add(initial_tensor, 2)
new_tensor

tensor([[20., 20., 20.],
        [20., 20., 20.]])

In [168]:
torch.add(initial_tensor, 10, new_tensor)

tensor([[218., 218., 218.],
        [218., 218., 218.]])

In [15]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

In [16]:
add1 = rand1 + rand2
add1

tensor([[1.6286, 0.4960, 0.4299],
        [3.4089, 1.8331, 1.8210]])

#### The add() method does an out-of-place add operation and returns a new tensor
This is assigned to the new_tensor variable

In [17]:
add2 = torch.add(rand1, rand2)
add2

tensor([[1.6286, 0.4960, 0.4299],
        [3.4089, 1.8331, 1.8210]])

In [18]:
tensor = torch.Tensor([[-1, -2, -3],
                       [ 1,  2,  3]])

#### Element-wise division
The div() and mul() functions can be used to divide and multiply the values in a tensor. Here, we do an element-wise division between two tensors

In [19]:
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

#### Element-wise multiplicaton

In [20]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

#### Clamp the value of a Tensor
There will be occasions where you would like to set upper and lower limits for the values in a tensor. This is where the clamp function is used. The value of an element is set to:
* min if if x<sub>i</sub> < min
* x<sub>i</sub> if min < x<sub>i</sub> < max
* max if x<sub>i</sub> > max

In [21]:
tensor_clamp = torch.clamp(tensor, min= -0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

## Vector Multiplication 

#### Dot product

In [22]:
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

In [23]:
dot_product = torch.dot(t1, t2) 
dot_product

tensor(50.)

#### Matrix Vector product
If mat is a (n×m) tensor, vec is a 1-D tensor of size m, out will be 1-D of size n.

In [24]:
matrix = torch.Tensor([[1, 2, 3],
                       [4, 5, 6]])

vector = torch.Tensor([0, 1, 2])

In [25]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

#### Matrix multiplication

In [26]:
another_matrix = torch.Tensor([[10, 30],
                               [20, 0],
                               [0 , 50]])

In [27]:
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

#### Returns the indices of the maximum values of a tensor across a dimension.

In [28]:
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

In [29]:
torch.argmin(matrix_mul, dim=1)

tensor([0, 0])