## Interoperablity between Numpy arrays and Pytorch Tensors

In [1]:
import numpy as np
import torch

#### Converting tensor to numpy arrays

In [2]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.6570, 0.7070, 0.7338],
        [0.9695, 0.9690, 0.2662],
        [0.7640, 0.7012, 0.2620],
        [0.0023, 0.0881, 0.1251]])

In [3]:
type(tensor)

torch.Tensor

### The numpy arrays use the same memory as the PyTorch tensor

In [4]:
numpy_from_tensor = tensor.numpy()                   
numpy_from_tensor

array([[0.65697277, 0.70697385, 0.7337888 ],
       [0.96950114, 0.96902645, 0.266222  ],
       [0.76399785, 0.70119935, 0.26203483],
       [0.00225097, 0.0880605 , 0.12509787]], dtype=float32)

In [5]:
type(numpy_from_tensor)

numpy.ndarray

In [6]:
torch.is_tensor(tensor)

True

In [7]:
torch.is_tensor(numpy_from_tensor)

False

#### The NumPy array and the Torch tensor share memory
numpy array is a view of the tensor

changes propogate between them

In [8]:
numpy_from_tensor[0, 0] = 100.0

numpy_from_tensor

array([[1.0000000e+02, 7.0697385e-01, 7.3378879e-01],
       [9.6950114e-01, 9.6902645e-01, 2.6622200e-01],
       [7.6399785e-01, 7.0119935e-01, 2.6203483e-01],
       [2.2509694e-03, 8.8060498e-02, 1.2509787e-01]], dtype=float32)

In [9]:
tensor

tensor([[1.0000e+02, 7.0697e-01, 7.3379e-01],
        [9.6950e-01, 9.6903e-01, 2.6622e-01],
        [7.6400e-01, 7.0120e-01, 2.6203e-01],
        [2.2510e-03, 8.8060e-02, 1.2510e-01]])

#### Converting a numpy array to a Tensor

In [10]:
numpy_arr = np.array([[1.0, 2.0, 3.0], 
                      [10.0, 20.0, 30.0],
                      [100.0, 200.0, 300.0]])

numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [11]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [14]:
type(tensor_from_numpy), torch.is_tensor(tensor_from_numpy)

(torch.Tensor, True)

#### The Numpy arrays and Tensor share the same memory
The tensor and numpy_from_tensor are shallow copies and share the same memory as the original numpy array. Modifying the original array affects the values of both tensor and numpy_from_tensor

In [15]:
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [16]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

#### Convert the data into a torch.Tensor. 

If the data is already a Tensor with the same dtype and device, no copy will be performed, otherwise a new Tensor will be returned

In [17]:
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

In [18]:
tensor_from_array_one = torch.as_tensor(np_array_one)
#creates a copy if the data is not already a tensor (only when needed)
#precludes unnecessary copies of data
tensor_from_array_one

tensor([4, 8], dtype=torch.int32)

In [19]:
np_array_one[1] = 5
np_array_one

array([4, 5])

In [20]:
tensor_from_array_one

tensor([4, 5], dtype=torch.int32)

#### torch.tensor() reads out the data from whatever it is passed, and constructs a leaf variable
deep copy of original underlying data (no shared mem)

In [21]:
np_array_two = np.array([2, 2])
np_array_two

array([2, 2])

In [22]:
tensor_from_array_two = torch.tensor(np_array_two)

tensor_from_array_two

tensor([2, 2], dtype=torch.int32)

#### in this method the tensor and array do not share memory

In [23]:
np_array_two[1] = 4
np_array_two

array([2, 4])

In [24]:
tensor_from_array_two

tensor([2, 2], dtype=torch.int32)