In [1]:
import torch 

from torch.autograd import Variable
#variables are now deprecated and not needed to store gradients
# objects are now stored as part of the tensor itself

#### We create a Variable with Float tensor

The return value is not a variable instead it is a tensor

In [2]:
var = Variable(torch.FloatTensor([9]))
var # returns a tensor anyway

tensor([9.])

In [3]:
var.requires_grad

False

In [4]:
var.requires_grad_()# used to enable Variable api functions

tensor([9.], requires_grad=True)

#### We create two weight variables with gradients enabled

In [5]:
w1 = Variable(torch.FloatTensor([3]), requires_grad = True)
w2 = Variable(torch.FloatTensor([7]), requires_grad = True)

In [6]:
w1

tensor([3.], requires_grad=True)

In [7]:
w2

tensor([7.], requires_grad=True)

#### We create two more variables using the weights

In [8]:
result_var = var * w1

result_var 

tensor([27.], grad_fn=<MulBackward0>)

#### New variables derive enabled gradients from weights

In [9]:
result_var.requires_grad

True

In [10]:
#calculate gradients for all of the input tensors
result_var.backward()

In [11]:
w1.grad

tensor([9.])

In [12]:
w2.grad

In [13]:
var.grad

tensor([3.])